import Head from 'next/head';
// import { Inter } from 'next/font/google'; // Commented out because it's not being used
import Layout from '@/components/Layout';
import Image from 'next/image';
import developer_image from '../../public/website images/developer_image.png.png';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { CircularText, LinkArrow } from '@/components/icons';
import HireMe from '@/components/HireMe';
import robobulb from '../../public/website images/robobulb.png.png';
import TransitionEffect from '@/components/TransitionEffect.js';
// const inter = Inter({ subsets: ['latin'] }); // Commented out because it's not being used

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect/>
       <main className='flex items-center text-black w-full min-h-screen '>
        <Layout className='pt-0 md:p-16 sm:pt-8'>
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/2'>
              <Image
                src={developer_image}
                alt='Digital Developer Image'
                className='h-auto w-full rounded-2xl'
                sizes='(max-width: 768px) 100vw ( max-width: 1200px) 50vw'
                priority
              />
            </div>
            <div className='flex flex-col items-center m-3 lg:w-full lg:flex-col lg:text-center '>
          <AnimatedText className='font-bold m-3 lg:text-center text-3xl md:text-2xl lg:text-3xl' text="Beyond Boundaries: Navigating the Digital Frontier with Generative AI and Cutting-Edge Web Development." />
              <p className='font-medium m-3 text-xl lg:text-l   '>Designing the next generation of digital experiences with generative AI and advanced web development techniques.</p>
              <div className='flex items-center self-start lg:self-center lg:mr-4'> {/* Adjusted margin value */}
                <Link
                  href='mailto:yahyafaraz1234@gmail.com'
                  target={'_blank'}
                  passHref
                  className='flex items-center bg-black capitalize text-white p-1 px-4 rounded-lg text-lg font-semibold
                   hover:bg-white border  hover:border-black   hover:text-black border-spacing-2 border-solid 
                   border-transparent  ml-2
                   md:px-4 md:text-base'
                  download={true}
                >
                  Contact Now
                  <LinkArrow className={'w-8 ml-2 flex flex-auto'} />
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <Image src={robobulb} alt={'robo bulb'} className='w-1/4 h-18 absolute right-0 -bottom-1/4 xl:hidden' />
      </main>
    </
    >
  );
}
